export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_BUSINESS = 'GET_BUSINESS';
export const ADD_BUSINESS = 'ADD_BUSINESS';
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';
export const BUSINESS_ERROR = 'BUSINESS_ERROR';
export const CLEAR_BUSINESS = 'CLEAR_BUSINESS';
export const CLEAR_BUSINESS_ERROR = 'CLEAR_BUSINESS_ERROR';

export const GET_CLIENTS = 'GET_CLIENTS';
export const ADD_CLIENT = 'ADD_CLIENT';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const CLIENT_ERROR = 'CLIENT_ERROR';
export const CLEAR_CLIENTS = 'CLEAR_CLIENTS';
export const CLEAR_CLIENT_ERRORS = 'CLEAR_CLIENT_ERRORS';
export const SET_CURRENT_CLIENT = 'SET_CURRENT_CLIENT';
export const CLEAR_CURRENT_CLIENT = 'CLEAR_CURRENT_CLIENT';
export const SET_DELETE_CLIENT = 'SET_DELETE_CLIENT';
export const CLEAR_DELETE_CLIENT = 'CLEAR_DELETE_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';

export const GET_EXPENSES = 'GET_EXPENSES';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const EXPENSE_ERROR = 'EXPENSE_ERROR';
export const CLEAR_EXPENSES = 'CLEAR_EXPENSES';
export const CLEAR_EXPENSE_ERRORS = 'CLEAR_EXPENSE_ERRORS';
export const SET_CURRENT_EXPENSE = 'SET_CURRENT_EXPENSE';
export const CLEAR_CURRENT_EXPENSE = 'CLEAR_CURRENT_EXPENSE';
export const SET_DELETE_EXPENSE = 'SET_DELETE_EXPENSE';
export const CLEAR_DELETE_EXPENSE = 'CLEAR_DELETE_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
