export const GET_INVOICES = 'GET_INVOICES';
export const ADD_INVOICE = 'ADD_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const SET_CURRENT_INVOICE = 'SET_CURRENT_INVOICE';
export const CLEAR_CURRENT_INVOICE = 'CLEAR_CURRENT_INVOICE';
export const FILTER_INVOICES = 'FILTER_INVOICES';
export const CLEAR_INVOICE_FILTER = 'CLEAR_INVOICE_FILTER';
export const INVOICE_ERROR = 'INVOICE_ERROR';
export const CLEAR_INVOICES = 'CLEAR_INVOICES';

export const GET_EXPENSES = 'GET_EXPENSES';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const SET_CURRENT_EXPENSE = 'SET_CURRENT_EXPENSE';
export const CLEAR_CURRENT_EXPENSE = 'CLEAR_CURRENT_EXPENSE';
export const FILTER_EXPENSES = 'FILTER_EXPENSES';
export const CLEAR_EXPENSE_FILTER = 'CLEAR_EXPENSE_FILTER';
export const EXPENSE_ERROR = 'EXPENSE_ERROR';
export const CLEAR_EXPENSES = 'CLEAR_EXPENSES';

export const GET_CLIENTS = 'GET_CLIENTS';
export const ADD_CLIENT = 'ADD_CLIENT';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const SET_CURRENT_CLIENT = 'SET_CURRENT_CLIENT';
export const CLEAR_CURRENT_CLIENT = 'CLEAR_CURRENT_CLIENT';
export const FILTER_CLIENTS = 'FILTER_CLIENTS';
export const CLEAR_CLIENT_FILTER = 'CLEAR_CLIENT_FILTER';
export const CLIENT_ERROR = 'CLIENT_ERROR';
export const CLEAR_CLIENTS = 'CLEAR_CLIENTS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';

export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_LOADING = 'SET_LOADING';
